Revert "Only allow using a single pkgpanda role on a host"
Breaks AWS Cloudformation clusters with:

```
pkgpanda.exceptions.InstallError: Machines can only have one role. Found
['aws', 'master', 'aws_master']
```

This reverts commit ee40043caca8a1e77484ff066dce4452ef4ae0d7.