Switch to using gradle for full build
This should resolve the issue we are seeing with Exhibitor crashing when
run with AWS as the backend store.... specifically:

```
Apr 17 20:30:12 ip-10-0-0-165.us-west-2.compute.internal systemd[1]:
Started Exhibitor Zookeeper Supervisor.
Apr 17 20:30:12 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
Starting Exhibitor for AWS
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
Exception in thread "main" java.lang.NoSuchMethodError:
com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:445)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:366)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at com.amazonaws.util.json.Jackson.<clinit>(Jackson.java:32)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.amazonaws.internal.config.InternalConfig.loadfrom(InternalConfig.java:200)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.amazonaws.internal.config.InternalConfig.load(InternalConfig.java:217)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:252)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:139)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:134)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:95)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:42)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:345)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.netflix.exhibitor.core.s3.S3ClientImpl.createClient(S3ClientImpl.java:268)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.netflix.exhibitor.core.s3.S3ClientImpl.changeCredentials(S3ClientImpl.java:75)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.netflix.exhibitor.core.s3.S3ClientImpl.<init>(S3ClientImpl.java:46)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.netflix.exhibitor.core.s3.S3ClientFactoryImpl.makeNewClient(S3ClientFactoryImpl.java:30)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.netflix.exhibitor.core.config.s3.S3ConfigProvider.<init>(S3ConfigProvider.java:121)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.netflix.exhibitor.standalone.ExhibitorCreator.getS3Provider(ExhibitorCreator.java:544)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.netflix.exhibitor.standalone.ExhibitorCreator.makeConfigProvider(ExhibitorCreator.java:300)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.netflix.exhibitor.standalone.ExhibitorCreator.<init>(ExhibitorCreator.java:170)
Apr 17 20:30:13 ip-10-0-0-165.us-west-2.compute.internal unshare[835]:
at
com.netflix.exhibitor.application.ExhibitorMain.main(ExhibitorMain.java:72)
```