Disable host lookups through mesos-dns on masters
This reverts commit 7806509b215db9e6be8852b6f2ac90c91ee03f31 as well as
disables mesos-dns host lookups on the masters. Exhibitor requires a
functioning DNS server... and as we update DNS, Exhibitor might crash,
gen_resolvconf will trigger, and Mesos will not be happy.

This is a problem we will need to resolve before we can run a node as a
master and slave at the same time. Example of the kind of Exhibitor
crash we might see:

```
INFO  com.amazonaws.http.AmazonHttpClient  Unable to execute HTTP
request: apollo-exhibitor.s3.amazonaws.com [ActivityQueue-0]
java.net.UnknownHostException: apollo-exhibitor.s3.amazonaws.com
```