Revert "Build pacakges directly rather than starting a subprocess of ourself"
This reverts commit ce0c40e0904971ddb2b9c460d670ac574c2480d1.

Broke the building with lots of odd errors in a number of cases.

Sample error:

Building: flask
Fetching sources
WARNING: Specifying docker explicitly should be avoided.
This option will be removed once enough of the dependencies are in pkgpanda form that everything can just use pkgpanda dependencies.
Auto-adding dependency: python-requests--f347eb1b570c30244670363c4753cc140c36ceb8
Package already added.
Auto-adding dependency: openssl--17605c1181df10eca17bc12c24da5a4fb3fb5129
Package already added.
Auto-adding dependency: python--d7a10982bcf31a9fb0d5b2a0ea6c762f6e23b077
Package already added.
Building package in docker
FATA[0002] Error response from daemon: Duplicate volume "/home/cody/projects/dcos-image/packages/boto/build": "/pkg/build" already in use, mounted from "/home/cody/projects/dcos-image/packages/flask/build"
ERROR: docker exited non-zero: 1
Command: docker run -v /home/cody/projects/dcos-image/packages/boto/build:/pkg/build:ro -v /home/cody/projects/dcos-image/packages/flask/src:/pkg/src:rw -v /tmp/pkgpanda_repocycxz6dd/python--d7a10982bcf31a9fb0d5b2a0ea6c762f6e23b077:/opt/mesosphere/packages/python--d7a10982bcf31a9fb0d5b2a0ea6c762f6e23b077:ro -v /home/cody/projects/dcos-image/packages/boto/src:/pkg/src:rw -v /home/cody/projects/dcos-image/packages/boto/result:/opt/mesosphere/packages/boto--7afb485dc8bc8521163885541878297d13e50326:rw -v /home/cody/projects/dcos-image/packages/flask/result:/opt/mesosphere/packages/flask--7dfaee71f1ecae1baeb41efa59870f853eef9afa:rw -v /tmp/pkgpanda-3h3lb_n2:/opt/mesosphere:ro -v /tmp/pkgpanda_repocycxz6dd/python-requests--f347eb1b570c30244670363c4753cc140c36ceb8:/opt/mesosphere/packages/python-requests--f347eb1b570c30244670363c4753cc140c36ceb8:ro -v /tmp/pkgpanda-z32hq6lg:/opt/mesosphere:ro -v /tmp/pkgpanda_repocycxz6dd/openssl--17605c1181df10eca17bc12c24da5a4fb3fb5129:/opt/mesosphere/packages/openssl--17605c1181df10eca17bc12c24da5a4fb3fb5129:ro -v /home/cody/projects/dcos-image/packages/flask/build:/pkg/build:ro -e PKG_VERSION=7dfaee71f1ecae1baeb41efa59870f853eef9afa -e PKG_PATH=/opt/mesosphere/packages/flask--7dfaee71f1ecae1baeb41efa59870f853eef9afa -e PKG_NAME=flask -e PKG_ID=flask--7dfaee71f1ecae1baeb41efa59870f853eef9afa dcos-builder /bin/bash -o nounset -o pipefail -o errexit /pkg/build